Спринт 13
Elena-Zarya/java-shareit pull request #1
Opened 2023-05-28 13:40 UTC by Elena-Zarya

2023-05-29 13:20 UTC, mikita95 requested changes
Все сделано очень хорошо :) Оставил несколько небольших замечаний

2023-05-29 13:20 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>   * TODO Sprint add-controllers.
Можно удалить неактуальный комментарий

2023-05-29 13:20 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>   * TODO Sprint add-controllers.
Можно удалить неактуальный комментарий

2023-05-29 13:20 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Collection<Item> allItems = itemStorage.getAllItems();
Можно было бы переписать этот же кусок в функциональном виде, было бы чуть короче

2023-05-29 13:20 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/model/User.java
> + * TODO Sprint add-controllers.
Можно удалить неактуальный комментарий

2023-05-29 13:20 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +    private final Map<Long, List<Long>> itemsByOwner = new HashMap<>();
Лучше перенести эту мапу (индекс) в репозиторий items, можно было бы сохранять в нее сразу при добавлении записи. Этот индекс больше про это

2023-05-29 13:20 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
Очень здорово, что придумали использовать mapstruct

2023-05-29 13:20 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private long id;
Управление id лучше перенести в хранилище, ведь это больше про способ хранения, чем просто бизнес-логику

2023-05-29 13:20 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private long id;
Управление id лучше перенести в хранилище, ведь это больше про способ хранения, чем просто бизнес-логику

2023-05-31 16:35 UTC, Elena-Zarya commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Collection<Item> allItems = itemStorage.getAllItems();
Никита, я не уверена, что правильно поняла комментарий. Заменила на 
Collection<Item> allItems = text.isEmpty() ? new ArrayList<>() : itemStorage.getAllItems(); 
Так лучше? или имелось в ввиду что-то другое?

2023-06-01 17:18 UTC, mikita95 approved these changes
Все сделано хорошо. Оставил еще пару замечаний, но они не критичные. Можно мержить пул-реквест

2023-06-01 17:18 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Collection<Item> allItems = text.isEmpty() ? new ArrayList<>() : itemStorage.getAllItems();
Имелось в виду, что можно переписать как:
```
if (text.isEmpty()) {
    return new ArrayList<>();
}
return itemStorage.getAllItems()
    .streams()
    .filter(item -> item.getAvailable() && (item.getName().toUpperCase().contains(text.toUpperCase())
                    || item.getDescription().toUpperCase().contains(text.toUpperCase())))
    .map(itemMapper::itemToDto)
    .toList();
```

2023-06-01 17:18 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +    Map<Long, Item> items = new HashMap<>();
Не хватает модификаторов, лучше отметить как `private final`

2023-06-11 11:36 UTC, merged