Спринт 14
Elena-Zarya/java-shareit pull request #2
Opened 2023-06-19 18:07 UTC by Elena-Zarya

2023-06-20 13:10 UTC, mikita95 requested changes
Все сделано хорошо. Оставил лишь несколько небольших замечаний

2023-06-20 13:10 UTC, mikita95 commented on pom.xml
> +<!--		<dependency>-->
Закомментированный код нужно удалить

2023-06-20 13:10 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                            @RequestHeader("X-Sharer-User-Id") Long userId) {
Для userId можно использовать примитивный long, этот аргумент обязателен

2023-06-20 13:10 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Лучше не использовать аннотацию lombok Data с сущностями hibernate. Проблема в том, что так сгенерируются методы equals(), hashCode() и toString(), которые если используются lazy или циклические зависимости между сущностями, все поломают. Лучше определить их руками, если нужно, так можно избежать ошибок в будущем.

Например, если сущность содержит lazy-поля, то они все равно добавятся в реализации этих методов. И каждый раз при их вызове будет происходить обращение в базу данных, что может понизить производительность приложения. Поэтому стоит руками точно указать реалиции методов equals(), hashCode() и toString(). Также если, например, классы A и B содержат ссылки друг на друга (например, отношение many-to-many), то при вызове метода toString на одном из них можно получить StackOverflowError, так как получится цикл.

2023-06-20 13:10 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public BookingResponseDto createBooking(BookingRequestDto bookingDtoRequest, Long userId) {
Лучше использовать транзакции (аннотация Transactional), так при параллельном исполнении запросов, база данных останется в консистентном состоянии.
Для методов, где проиходит только чтения, стоит использовать флаг readOnly

2023-06-20 13:10 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (comments.size() != 0) {
Лучше использовать метод isEmpty

2023-06-20 13:10 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                assert allItemsByName != null;
assert не нужно использовать в production коде, так как эти проверки включаются только при передаче специального флага, а также не генерируют понятную ошибку

2023-06-20 13:10 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (lastBookingsByItem.size() > 0) {
isEmpty

2023-06-20 13:10 UTC, mikita95 commented on src/main/resources/schema.sql
> +  status VARCHAR(512),
Статус не может быть null

2023-06-20 22:11 UTC, Elena-Zarya commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Никита, спасибо больше за подробное объяснение! Выполняя это тз, вероятно, я столкнулась с этой ошибкой. У меня создавался цикл, когда я пыталась обращать из itemservis к bookingservis.

2023-06-21 18:11 UTC, mikita95 approved these changes
Все хорошо. Можно мержить пул-реквест

2023-06-21 18:11 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public int hashCode() {
В целом, так работает :) Можно прочитать документацию hibernate https://docs.jboss.org/hibernate/core/4.0/manual/en-US/html/persistent-classes.html#persistent-classes-equalshashcode - там более подробно указано как реализовать hashCode и equals в сущностях hibernate

2023-06-24 09:18 UTC, merged