Спринт 15.
Elena-Zarya/java-shareit pull request #3
Opened 2023-07-06 22:07 UTC by Elena-Zarya

2023-07-07 14:50 UTC, mikita95 requested changes
Все сделано просто отлично. Оставил лишь небольшие рекомендации

2023-07-07 14:50 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (from < 0 || size < 1) {
Можно вынести эту логику валидации и получения PageRequest в утилитный класс, чтобы не дублировать код

2023-07-07 14:50 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDto getItemRequestById(Long requestId, long userId) {
Здесь стоит использовать Transactional с readOnly=true, так как метод содержит несколько читающих запросов

2023-07-07 15:54 UTC, Elena-Zarya commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDto getItemRequestById(Long requestId, long userId) {
Никита, спасибо) Я поставила аннотацию @Transactional(readOnly = true) на уровне класса (где-то встречала эту рекомендацию) и переопределила ее на на @Transactional только над методом createItemRequest. А остальные методы в этом классе только получают данные из базы данных, поэтому не ставила над ними отдельно аннотации. Лучше поставить над каждым методом отдельно и так будет нагляднее? Или дело в чем-то другом?

2023-07-08 10:21 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDto getItemRequestById(Long requestId, long userId) {
Отличное решение, сделать методы read only по-умолчанию, так точно запросы не будут выполнять лишних операций записи

2023-07-08 10:22 UTC, mikita95 approved these changes
Все хорошо. Можно мержить пул-реквест

2023-07-08 12:21 UTC, merged